services:
  - type: web
    name: first-spring-app
    env: docker
    branch: feature/security-and-render-deploy
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: dev
      - key: SERVER_CONNECTION_TIMEOUT
        value: 120000
      - key: SERVER_READ_TIMEOUT
        value: 120000